### PR TITLE
Support release process for opensearch-testcontainers

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Support release process for `opensearch-testcontainers`. Adding neccessary Jenkins build pipelines for releases and snapshots.

### Issues Resolved
Closes https://github.com/opensearch-project/opensearch-testcontainers/issues/15 and https://github.com/opensearch-project/opensearch-build/issues/2656

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@peterzhuamazon the placeholder for webhook token `jenkins-opensearch-testcontainers-generic-webhook-token`, thank you!

**Comment by peterzhuamazon** [comment]
`jenkins-opensearch-testcontainers-generic-webhook-token` is great that is actually the exact name I used for internal deployment :)

**Comment by peterzhuamazon** [comment]
Please add these as the option to this workflow:
```
options {
        timeout(time: 30, unit: 'MINUTES')
        throttleJobProperty(
            categories: [],
            limitOneJobWithMatchingParams: false,
            maxConcurrentPerNode: 0,
            maxConcurrentTotal: 1,
            paramsToUseForLimit: '',
            throttleEnabled: true,
            throttleOption: 'project',
        )
    }
```

**Review by zelinh — APPROVED** [review]
After syncing up and validating with @reta and @peterzhuamazon, approving this to proceed.

**Pull request merged**
